CSS/styleadmin.css, PHP/ingresoadmin.php
Cree un toggle que cambia de div sin salir de la pagina, emplea html, jquery y estilos
=> Actualizacion ingresoadmin.php

.vscode/settings.json
se elimino un archivo innecesario del pull request
=> borrar archivo obsoleto

CSS/style.css, SOPIEC/assets/css/style.css, SOPIEC/assets/js/validaciones.js, SOPIEC/assets/php/actualizar.php, SOPIEC/assets/php/guardarinfo.php, SOPIEC/index.php, SOPIEC/login.html, SOPIEC/modificar.php, SOPIEC/nuevousuario.php, SOPIEC/usuarios.php, index.php
Tambien hice pequeños cambios en el css del login, cambie los bordes
=> Correccion de alertas

SOPIEC/assets/css/style.css, SOPIEC/assets/php/borrar.php, SOPIEC/assets/php/guardarinfo.php, SOPIEC/usuarios.php
Se mejoro la alerta, se mejoró la tabla
=>  Cambios alertas

SOPIEC/assets/php/actualizarequipo.php, SOPIEC/assets/php/borrar.php, SOPIEC/assets/php/buscarusuario.php, SOPIEC/assets/php/logout.php, SOPIEC/assets/php/validacion.php, SOPIEC/equipos.php, SOPIEC/index.php, SOPIEC/modificar.php, SOPIEC/modificarequipo.php, SOPIEC/nuevoequipo.php, SOPIEC/nuevousuario.php, SOPIEC/usuarios.php, contactenos.php
El login funciona correctamente, pero hay un  bug, cuando se entra como admin y se edita, elimina o modifica algún equipo o usuario la sesion se destruye y redirige al login.html
Corregi tambien una animacion en el contacto.php y las rutas de los iconos de redes, ademas las alertas de ambos crud ya funcionan correctamente
=> Edicion de archivos para dejar funcional el login

SOPIEC/assets/css/style.css, SOPIEC/assets/php/actualizar.php, SOPIEC/assets/php/borrar.php, SOPIEC/assets/php/buscarusuario.php, SOPIEC/assets/php/guardarinfo.php, SOPIEC/nuevousuario.php
Se añadió nueva vista al actualizar user, y se corrigieron variables de alerta, nota: aún persite  la alerta.
=> Nueva vista al actualizar un usuario

SOPIEC/assets/css/style.css, SOPIEC/assets/js/validaciones.js, SOPIEC/assets/php/actualizar.php, SOPIEC/assets/php/buscarusuario.php, SOPIEC/assets/php/guardarinfo.php, SOPIEC/modificar.php, SOPIEC/nuevousuario.php
Ahora se muestran los datos del usuario de forma sencilla, al agregar un usuario muestra y da las opciones de ir a los usuarios o agregar un usuario más
Nota: hay un pequeño bug con la variable rol que debo resolver.
=> Se añadieron las vistas de datos actualizar y agregar nuevo user

docs/diagramas.html, docs/dvleasy.html, docs/index.html, docs/nosotros.html
agregue a la pagina de documentacion en enlazamiento de los link de las redes y tambien los iconos.
=> Redes y iconos

SOPIEC/assets/js/validaciones.js, SOPIEC/equipos.php
añadi el resto de alertas a los campos de lod formualrios nuevoequipo y actualizarequipo
=> correciones finales alertas CRUD nuevoequipo actualizarequipo

SOPIEC/assets/php/db.php, SOPIEC/index.php
index.php: se arreglo el error de datos repetidos en usuarios y la no vista de los equipos.
db.php cambie los datos directos por variables para en el futuro poder cambiar facilmente esos campos por bases de datos en linea.
=> index.php y db.php correcciones

SOPIEC/assets/css/style.css, SOPIEC/assets/php/asignarEquipo.php, SOPIEC/index.php
He creado dos tablas en una se listan los equipos y en la otra los usuarios, con un botón asignar .
=> Vista de asignación de equipos

SOPIEC/index.php, SOPIEC/index_user.php, SOPIEC/mostrartickets.php, SOPIEC/nuevoequipo.php, SOPIEC/verticket.php
se creo una seccion para ver los tickets creados por los users
=> seccion ver tickes - Admin :

SOPIEC/vista_usuario.php
se había borrado el archivo de conexión de la base de datos con la vista impidiendo hacer el query.
=> solucion vista_usuario.php

SOPIEC/assets/js/asignacion.js, SOPIEC/assets/php/actualizar.php, SOPIEC/assets/php/actualizarequipo.php, SOPIEC/assets/php/borrar.php, SOPIEC/assets/php/borrarequipo.php, SOPIEC/assets/php/buscarequipo.php, SOPIEC/assets/php/buscarusuario.php, SOPIEC/assets/php/deshacerAsignacion.php, SOPIEC/assets/php/guardarequipo.php, SOPIEC/assets/php/guardarinfo.php, SOPIEC/equipos.php, SOPIEC/equiposAsignados.php, SOPIEC/index.php, SOPIEC/mostrartickets.php, SOPIEC/usuarios.php
-Ahora se puede eliminar la asignación de equipos a usuarios y rehacer (Queda un bug por solucionar, si el usuario tiene más de un equipo, al eliminar una asignación se borran todas)
-Correjí las rutas  de sesion en varios archivos, dado que dañaban el funcionamiento del software
-Añadí un SetTimeOut para los mensajes flash de javascript (Antes no se podian leer debido al rapido recargo de la pagina)
-Añadí multiples metodos de busqueda de un equipo (Antes era solo por el serial)
=> Deshacer asignaciones de equipos, corrección de sesiones etc

SOPIEC/assets/php/actualizar.php, SOPIEC/mostrartickets.php, SOPIEC/ticket.php, SOPIEC/verticket.php, SOPIEC/vista_usuario.php
Se solucionan los errores de este issue:
-Al darle en tickets desde la vista de admin se cierra la sesión. (solucionado)
-Se borró el identificador azul que se había puesto hace rato en la vista "Mi usuario" para resaltar los datos del user. (solucionado)
-En la opción "Open Ticket" de la vista usuario pasa lo mismo, bota de la sesión. (solucionado)
=> Errores terceros solución 

SOPIEC/index.php, SOPIEC/miequipo_user.php, SOPIEC/nuevousuario.php
#125 
-Ahora el usuario puede ver su equipo registrado, en caso de que no tenga ninguno asignado aún saldrá una alerta tipo"Danger"
-Se añadió un icono eye para visualizar la contraseña en texto claro cuando se añade un usuario nuevo.
=> Funcionalidad "Ver mi equipo", Botón "Mostrar contraseña"

SOPIEC/assets/js/asignacion.js, SOPIEC/assets/php/actualizar.php, SOPIEC/assets/php/actualizarequipo.php, SOPIEC/assets/php/checkearDisponibilidad.php, SOPIEC/equipos.php, SOPIEC/equiposAsignados.php, SOPIEC/index.php
-Correjidos los bugs en los que se podian enviar datos en blanco en el select.
-Ahora el botón asignar estará inhabilitado hasta que se seleccionen ambos campos (Un usuario y un equipo.)
=> Validaciones de asignaciones de equipos

SOPIEC/miequipo_user.php
Ahora la vista identifica cuando tiene y cuando no tiene equipos, evitando así la alerta innecesaria al cargar todos los equipos, ademas se identifica si hay dos o mas equipos (mis equipos) o si solo hay uno o ninguno (mi equipo).
=> issue #133 Solucionado 

SOPIEC/assets/php/guardarsolucion.php, SOPIEC/equipos.php, SOPIEC/mostrartickets.php, SOPIEC/nuevoequipo.php, SOPIEC/ticket.php, SOPIEC/verticket.php
se añadio la opcion al admin de cambiar el estado del ticket y responder elmismo mediante campos adicionales en el form desde la vista verticket
=> responder tickets 

SOPIEC/assets/css/style.css, SOPIEC/assets/modelos/avatar_admin.php, SOPIEC/assets/php/actualizar_avatar.php, SOPIEC/assets/php/avatar_seleccion.php, SOPIEC/assets/php/eliminar_avatar.php, SOPIEC/equipos.php, SOPIEC/index.php, SOPIEC/mostrartickets.php, SOPIEC/nuevoequipo.php, SOPIEC/nuevousuario.php, SOPIEC/perfil.php, SOPIEC/usuarios.php
Ademas de mostrar el avatar en cada vista principal se agregó nuevo metodo de perfil:
- El usuario sólo podrá tener una imagen de perfil por sesion, asi evitamos la sobrecarga al server.
- El usuario cada que coloque la nueva foto de perfil la anteriores se eliminarán.
- El usuario NO puede ver las imágenes de la bd.
- El usuario en caso de querer eliminar la foto, esta se reemplazará por la foto default (valor 1).
=> solucion al issue 139

contactenos.php
=> contactenos.php

SOPIEC/assets/js/validaciones.js, SOPIEC/assets/php/actualizarDatosUser.php, SOPIEC/index.php, SOPIEC/miequipo_user.php, SOPIEC/modificar.php, SOPIEC/vista_usuario.php
-Ahora el usuario podrá actualizar sus datos personales incluyendo la contraseña (Aún en desarrollo, faltan validaciones y otros detalles).
=> Primera parte de "Editar mis datos"

SOPIEC/assets/css/style.css, SOPIEC/assets/js/validaciones.js, SOPIEC/assets/php/actualizarDatosUser.php, SOPIEC/modificar.php, SOPIEC/vista_usuario.php
Ahora el usuario podrá actualizar rapidamente sus datos y su contraseña desde el apartado "Ver mi usuario registrado"
=> Funcionalidad Actualizar datos, Actualizar contraseña

SOPIEC/assets/modelos/navbar_header_user.php, SOPIEC/assets/php/guardarticket.php, SOPIEC/ticket.php, SOPIEC/ticketsenviados.php, SOPIEC/verticketUser.php
- Se añadio una vista nueva para user en la cual el user puede observar el estado de los tickets creados por el mismo, y verificar si ha sido respondido o no
- Se agrego el campo de Cedula tanto como a la DB como a loc campos de tickets, esto con el fin de poder relacionar los tickets  con un serial unico almomento de mostrarselos al user, es decir, para poderlos encontrar despues y desplegarlos todos en la vista creada en la seccion de user.
=> Vista de tickets creados - Cambios en formato de ticket 

SOPIEC/assets/php/guardar.php, SOPIEC/vista_usuario.php
Anteriormente existía un bug el cual no permitía eliminar los avatares, sin embargo ese bug ya fue solucionado.
=> Solucionado bug avatar

SOPIEC/assets/js/validaciones.js, SOPIEC/assets/php/actualizarDatosAdmin.php, SOPIEC/equiposAsignados.php, SOPIEC/perfil.php
Ahora el admin puede actualiar sus datos tal cual como el usuario
=> Actualizar datos Admin

SOPIEC/ticket.php, SOPIEC/verticket.php, SOPIEC/verticketUser.php
solucionado el responsive en resoluciones  mayores a 1366x720p
=> ticket correciones de responsive

SOPIEC/assets/modelos/navbar_header_admin_vp.php, SOPIEC/verticket.php
- correciones en el sidebar de ticket 
- correciones ortograficas
- correciones en el heaader
=> correciones de ticket

SOPIEC/assets/css/style.css, SOPIEC/info.php, SOPIEC/manuales.php, SOPIEC/mostrartickets.php, SOPIEC/ticketsenviados.php, SOPIEC/verticket.php
- Se añadieron Iconos en ver tickets
=> Iconos en ver tickets

SOPIEC/assets/css/style.css, SOPIEC/perfil.php
habia problema en la ruta de la foto, sin embargo ya fue solucionado
=> solución issue #178

SOPIEC/assets/modelos/navbar_header_admin_vp.php, SOPIEC/historialdetickets.php, SOPIEC/vistahistorial.php
- añadida la vista para usuarios admin  de los tickets resueltos en una seccion diferente, esto con el fin de descongestionar la cantidad de tickets que habian en una sola vista
- cambie el sidebar de admin volviendo la seccion ticket una lista desplegable con los items  "tickets pendientes" y "historial de tickets"
=> vista inicial- historial de tickets

JS/alertas-contacto.js, PHP/db.php, contactenos.php
- se agregaron las alertas en la seccion de contactenos en la landing page
=> alertas - seccion contactenos

SOPIEC/assets/modelos/vpa_admin.php, SOPIEC/assets/modelos/vpa_user.php, SOPIEC/equipos.php, SOPIEC/excel.php, SOPIEC/exportaciones.php, SOPIEC/forgotpass.php, SOPIEC/index.php, SOPIEC/index_user.php, SOPIEC/perfil.php, SOPIEC/primer-acceso_admin.php, SOPIEC/primer-acceso_user.php, SOPIEC/vista_usuario.php
#227: En el apartado de usuarios se puede ver un icono en forma de hoja el cual sirve para crear un archivo Excel de los equipos, generando una copia física para su envió a terceros sin tener que dar acceso directo a SOPIEC
#228: Ahora al ingresar el usuario por primera vez sea admin o user, lo redirigirá a otra pagina en la cual queda inhabilitado el acceso a SOPIEC, de manera que debe cambiar la contraseña de manera obligatoria.
las únicas opciones en esa interfaz son cambiar la contraseña y cerrar sesión.
=> Issues: #227, #228 resueltos.

SOPIEC/assets/php/validacion.php, opiniones.php
Anteriormente el primer comentario no se veia, corregido.
=> Solucion comentarios
